"""
Predictable Structure Detection Service.
Identifies common human psychological password structuring habits:
  - Capital letter at start + common word + simple digits + symbol (e.g., 'Password123!', 'Welcome@123')
  - Word + Year pattern (e.g., 'admin2026', 'summer2024')
  - Word + sequential/predictable numbers (e.g., 'hello1234', 'test123')
Rule-based brute-force engines specifically target these exact mutation templates.
"""

import re
from typing import Dict, Any, List


def detect_predictable_structure(password: str) -> Dict[str, Any]:
    """
    Detects formulaic structures commonly generated by humans trying to satisfy composition rules.

    Returns:
      Dict with has_predictable_structure, patterns, penalty, and details.
    """
    if not password:
        return {
            "has_predictable_structure": False,
            "patterns": [],
            "penalty": 0,
            "details": []
        }

    patterns: List[str] = []
    details: List[str] = []
    penalty = 0

    # 1. TitleCase + Digits + Special Symbol (The classic 'Password123!' archetype)
    classic_composition_regex = r'^[A-Z][a-z]{3,}[0-9]{1,4}[!@#$%^&*()_+\-=\[\]{};:\'",.<>/?]$'
    if re.match(classic_composition_regex, password):
        patterns.append("Classic TitleCase + Digits + Symbol Template")
        details.append(
            "Matches the predictable template: Capitalized Word + Number + Trailing Symbol "
            "(e.g., 'Password123!'). This structure is prioritized by rule-based password cracking masks."
        )
        penalty += 20

    # 2. Word + Year pattern (years 1940 - 2035)
    year_match = re.search(r'(19[4-9][0-9]|20[0-3][0-9])', password)
    if year_match:
        year_str = year_match.group(0)
        patterns.append(f"Year Pattern ({year_str})")
        details.append(
            f"Contains a 4-digit calendar year '{year_str}'. Attackers frequently test birth years, "
            "graduation years, or current/upcoming years in credential stuffing attacks."
        )
        penalty += 15

    # 3. Trailing or leading common numbers (e.g., word + 123, 1234, 007, 1)
    if re.search(r'[a-zA-Z]+(123|1234|007|01|111|999|777)$', password):
        patterns.append("Word with Predictable Numeric Suffix")
        details.append("Appends a predictable numeric sequence to a word instead of true randomness.")
        penalty += 12

    # 4. Symbol padding at ends (e.g., '!password!', '@welcome#')
    if re.match(r'^[!@#$%^&*()_+\-=\[\]{}].+[!@#$%^&*()_+\-=\[\]{}]$', password):
        patterns.append("Border Symbol Wrapping")
        details.append("Uses special characters only as decorative bookends, which password crackers easily strip and test.")
        penalty += 8

    penalty = min(25, penalty)

    return {
        "has_predictable_structure": len(patterns) > 0,
        "patterns": patterns,
        "penalty": penalty,
        "details": details
    }
